name: tests

on:
  push:
    branches:
      - "t*"
  pull_request:
    branches:
      - "t*"

jobs:
  test:
    uses: CursorCult/.github/.github/workflows/test-rule.yml@main
    with:
      python-version: "3.12"
